dist: bionic
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

notifications:
  email: true

# command to install dependencies
install:
  - pip install flake8 PyYAML argparse rospkg catkin_pkg defusedxml
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros-latest.list'
  - sudo apt -qq update
  - sudo apt -qq install -y ros-melodic-catkin ros-melodic-roslaunch ros-melodic-rostest ros-melodic-roslint

before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  # prepare workspace
  - source /opt/ros/melodic/setup.bash
  - export ROS_PYTHON_VERSION=$(python -c "import sys; print(sys.version_info[0])")

# command to run tests
script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/install -DSETUPTOOLS_DEB_LAYOUT=OFF ..
  - make install
  - source /tmp/install/setup.bash
  - make test
  - catkin_test_results
